#pragma once


namespace Client
{
	enum LEVEL {
		LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY,
		LEVEL_MOO, LEVEL_HERO, LEVEL_WOO, LEVEL_YU, LEVEL_HYEOK, LEVEL_TOOL,
		LEVEL_END
	};

	enum COLLISION_GROUP {
		COLLISION_PLAYER, COLLISION_MONSTER,
		COLLISION_NON_PHYSIC_BLOCK, COLLISION_BLOCK,
		COLLISION_END
	};

	
	enum BLOCKTYPE { DIRT, GRASSDIRT, STONE, IRONORE, COALORE, WOOD, LEAF, BLOCKTYPE_END };

	enum ITEMTYPE { ITEM_DIRT, ITEM_COBBLESTONE, ITEM_RAWIRON, ITEM_COAL, ITEM_WOOD, ITEM_SAPLING, ITEM_APPLE, ITEM_SEED, ITEM_REDTULIP, ITEM_END };


	enum ITEMID	{ ITEMID_FOOD, ITEMID_ARMOR, ITEMID_BLOCK, ITEMID_END};
	enum ITEMNAME { ITEMNAME_WOOD, ITEMNAME_OAKPLANKS, ITEMNAME_COBBLESTONE, ITEMNAME_DIRT, ITEMNAME_DANDELION, ITEMNAME_QUEST, ITEMNAME_RAWIRON, ITEMNAME_COAL, ITEMNAME_SAPLING,
		ITEMNAME_APPLE, ITEMNAME_SEED, ITEMNAME_REDTULIP, ITEMNAME_END };

	// 인벤에 저장될 때 ITEMID 구분이 되야함
	// 1. 손에 들었을 떄 Rect 인지 Cube 구분이 되야함 그래야 올바른 텍스쳐를 입힐 수 있음

}