#pragma once


namespace Client
{
	enum LEVEL {
		LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY,
		LEVEL_MOO, LEVEL_HERO, LEVEL_WOO, LEVEL_YU, LEVEL_HYEOK, LEVEL_TOOL,
		LEVEL_END
	};

	enum COLLISION_GROUP {
		COLLISION_PLAYER, COLLISION_MONSTER,
		COLLISION_NON_PHYSIC_BLOCK, COLLISION_BLOCK,
		COLLISION_END
	};

	
	enum BLOCKTYPE { DIRT, GRASSDIRT, STONE, IRONORE, COALORE, WOOD, LEAF, BLOCKTYPE_END };

	enum ITEMID	{ ITEMID_FOOD, ITEMID_ARMOR, ITEMID_BLOCK, ITEMID_END};
	enum ITEMNAME { ITEMNAME_WOOD, ITEMNAME_OAKPLANKS, ITEMNAME_COBBLESTONE, ITEMNAME_DIRT, ITEMNAME_DANDELION, ITEMNAME_QUEST, ITEMNAME_RAWIRON, ITEMNAME_COAL, ITEMNAME_SAPLING,
		ITEMNAME_APPLE, ITEMNAME_SEED, ITEMNAME_REDTULIP, ITEMNAME_STONE, ITEMNAME_GRASSDIRT, ITEMNAME_IRONORE, ITEMNAME_COALORE, ITEMNAME_GRASS, ITEMNAME_LEAF, ITEMNAME_END };
}
