#pragma once


namespace Client
{
	enum LEVEL {
		LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY,
		LEVEL_MOO, LEVEL_HERO, LEVEL_WOO, LEVEL_YU, LEVEL_HYEOK, LEVEL_TOOL,
		LEVEL_END
	};

	enum COLLISION_GROUP {
		COLLISION_PLAYER, COLLISION_MONSTER,
		COLLISION_NON_PHYSIC_BLOCK, COLLISION_BLOCK,
		COLLISION_END
	};

	
	enum BLOCKTYPE { DIRT, GRASSDIRT, STONE, IRONORE, COALORE, WOOD, LEAF, BLOCKTYPE_END };

	enum ITEMID	{ ITEMID_FOOD, ITEMID_ARMOR, ITEMID_BLOCK, ITEMID_END};

	/*enum ITEMNAME { ITEMNAME_WOOD, ITEMNAME_OAKPLANKS, ITEMNAME_COBBLESTONE, ITEMNAME_DIRT, ITEMNAME_DANDELION, ITEMNAME_QUEST, ITEMNAME_RAWIRON, ITEMNAME_COAL, ITEMNAME_SAPLING,
	ITEMNAME_APPLE, ITEMNAME_SEED, ITEMNAME_REDTULIP, ITEMNAME_STONE, ITEMNAME_GRASSDIRT, ITEMNAME_IRONORE, ITEMNAME_COALORE, ITEMNAME_GRASS, ITEMNAME_LEAF, ITEMNAME_END };*/


	enum ITEMNAME
	{
		ITEMNAME_DIRT, ITEMNAME_GRASSDIRT, ITEMNAME_STONE, ITEMNAME_COBBLESTONE, ITEMNAME_WOOD, ITEMNAME_OAKPLANKS, ITEMNAME_LEAF, 
		ITEMNAME_CUBE_END,
		
		ITEMNAME_SEED = 100, ITEMNAME_SAPLING, ITEMNAME_APPLE, ITEMNAME_REDTULIP, ITEMNAME_DANDELION, ITEMNAME_COAL, ITEMNAME_RAWIRON, ITEMNAME_IRON,
		ITEMNAME_SWORD, ITEMNAME_PICKAXE, ITEMNAME_TORCH, ITEM_WEPON_1, ITEM_WEPON_2, ITEM_WEPON_3, ITEM_WEPON_4, ITEM_WEPON_5, ITEMNAME_RECT_END,


		ITEMNAME_IRONORE = 900, ITEMNAME_COALORE, ITEMNAME_GRASS,
		ITEMNAME_END = 999
	};


}

